version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - /mnt/nextcloud/redis:/data
    networks:
      nextcloud_net:
        ipv4_address: 172.22.1.3

networks:
  nextcloud_net:
    external: true
    name: nextcloud_nextcloud_net  # Nombre generado por el primer compose